apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-medium
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  destination:
    namespace: 'map-stage'
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/staging/staging-medium
    repoURL: 'https://github.com/CrunchyDemos/pg-clusters-managed.git'
  project: crunchydata-postgres-operator
  syncPolicy:
    automated: {}