apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-medium
  namespace: argocd
spec:
  destination:
    namespace: 'geotest'
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/staging/staging-medium
    repoURL: 'https://github.com/CrunchyDemos/pg-clusters-managed.git'
  project: geomap-databases
