apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-small
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'geotest'
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/development/dev-small
    repoURL: 'https://github.com/CrunchyDemos/pg-clusters-managed.git'
    targetRevision: HEAD
  project: default
